Repository 3rd-wanted-pre-onboarding-team-D/03-GameDuo-wanted-D, pull requests merged in 2022-07, with the labels that each got.

#3 Setting: Project Initialize
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/boss-raid/boss-raid.controller.spec.ts
  src/boss-raid/boss-raid.controller.ts
  src/boss-raid/boss-raid.module.ts
  src/boss-raid/boss-raid.providers.ts
  src/boss-raid/boss-raid.service.spec.ts
  src/boss-raid/boss-raid.service.ts
  src/constants.ts
  src/entity/raid-record.entity.ts
  src/entity/user.entity.ts
  src/http-exception.filter.ts
  src/main.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.providers.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
  typeorm.module.ts
  typeorm.providers.ts
  webpack-hmr.config.js
Labels: Setting, Feat

#10 Feat : 레이드 랭킹관련 모듈 생성
  package-lock.json
  package.json
  src/app.module.ts
  src/boss-raid/boss-raid.module.ts
  src/boss-raid/boss-raid.service.ts
  src/ranking/ranking.module.ts
  src/ranking/ranking.service.spec.ts
  src/ranking/ranking.service.ts
Labels: Feat

#12 feat: 유저 생성, 조회 구현 (#7)
  package-lock.json
  package.json
  src/user/dto/create-user.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  typeorm.providers.ts
Labels: Feat

#17 Fix: develop -> Master Conflict 해결
  docker-compose.redis.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/boss-raid/boss-raid.controller.ts
  src/boss-raid/boss-raid.module.ts
  src/boss-raid/boss-raid.service.ts
  src/boss-raid/dto/raid-end-request.dto.ts
  src/boss-raid/dto/raid-status.dto.ts
  src/entity/raid-record-type.ts
  src/entity/raid-record.entity.ts
  src/ranking/ranking.module.ts
  src/ranking/ranking.service.spec.ts
  src/ranking/ranking.service.ts
  src/user/dto/create-user.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  tsconfig.json
  typeorm.providers.ts
Labels: fix

#21 fix: docker-compose.redis npm 명령어 추가 (#1)
  package.json
Labels: Setting
